<?php

namespace Database\Seeders;

use App\Models\Art;
use Illuminate\Database\Seeder;

class ArtSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'artID' => '1',
                'username' => 'minglee',
                'artistName' => 'Nor Tijan Firdaus',
                'artName' => 'After Ma Jolie',
                'artImg' => 'Img/Artwork/After Ma Jolie.jpg',
                'category_id' => '2',
                'artStyle' => 'Sculpture',
                'artPrice' => '7500',
                'artDesc' => 'E-waste on wood coated with 2k matte epoxy resin',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2020',
                'artWidth' => '194',
                'artHeight' => '117',
                'datetime' => '2022-11-18 00:50:10',
                'created_at' => '2022-11-18 00:50:10',
                'updated_at' => '2022-11-18 00:50:10',
            ],
            [
                'artID' => '2',
                'username' => 'minglee',
                'artistName' => 'Nor Tijan Firdaus',
                'artName' => 'After Pago Pago',
                'artImg' => 'Img/Artwork/After Pago Pago.jpg',
                'category_id' => '2',
                'artStyle' => 'Sculpture',
                'artPrice' => '3000',
                'artDesc' => 'E-waste on wood coated with 2k matte epoxy resin',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2020',
                'artWidth' => '194',
                'artHeight' => '117',
                'datetime' => '2022-12-03 00:50:10',
                'created_at' => '2022-12-03 00:50:10',
                'updated_at' => '2022-12-03 00:50:10',
            ],
            [
                'artID' => '3',
                'username' => 'minglee',
                'artistName' => 'Nor Tijan Firdaus',
                'artName' => 'After The Kiss',
                'artImg' => 'Img/Artwork/After The Kiss.jpg',
                'category_id' => '2',
                'artStyle' => 'Sculpture',
                'artPrice' => '2500',
                'artDesc' => 'E-waste on wood coated with 2k matte epoxy resin',
                'artStatus' => 'SOLD',
                'artYear' => '2020',
                'artWidth' => '128',
                'artHeight' => '98',
                'datetime' => '2022-11-29 00:50:10',
                'created_at' => '2022-11-29 00:50:10',
                'updated_at' => '2022-11-29 00:50:10',
            ],
            [
                'artID' => '4',
                'username' => 'minglee',
                'artistName' => 'Nor Tijan Firdaus',
                'artName' => 'After Endearing Thoughts',
                'artImg' => 'Img/Artwork/After Endearing Thoughts.jpg',
                'category_id' => '2',
                'artStyle' => 'Sculpture',
                'artPrice' => '4500',
                'artDesc' => 'E-waste on wood coated with 2k matte epoxy resin',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2020',
                'artWidth' => '128',
                'artHeight' => '98',
                'datetime' => '2022-11-15 23:12:10',
                'created_at' => '2022-11-15 23:12:10',
                'updated_at' => '2022-11-15 23:12:10',
            ],
            [
                'artID' => '5',
                'username' => 'minglee',
                'artistName' => 'Nor Tijan Firdaus',
                'artName' => 'After the Amber Necklace',
                'artImg' => 'Img/Artwork/After the Amber Necklace.jpg',
                'category_id' => '4',
                'artStyle' => 'Sculpture',
                'artPrice' => '3000',
                'artDesc' => 'E-waste on wood coated with 2k matte epoxy resin',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2020',
                'artWidth' => '128',
                'artHeight' => '98',
                'datetime' => '2022-11-25 00:34:10',
                'created_at' => '2022-11-15 23:12:10',
                'updated_at' => '2022-11-15 23:12:10',
            ],
            [
                'artID' => '6',
                'username' => 'minglee',
                'artistName' => 'Nor Tijan Firdaus',
                'artName' => 'After Murid Sekolah',
                'artImg' => 'Img/Artwork/After Murid Sekolah.jpg',
                'category_id' => '2',
                'artStyle' => 'Sculpture',
                'artPrice' => '2200',
                'artDesc' => 'E-waste on wood coated with 2k matte epoxy resin',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2020',
                'artWidth' => '128',
                'artHeight' => '98',
                'datetime' => '2022-10-18 12:50:10',
                'created_at' => '2022-10-18 12:50:10',
                'updated_at' => '2022-10-18 12:50:10',
            ],
            [
                'artID' => '7',
                'username' => 'minglee',
                'artistName' => 'Adam Ummar',
                'artName' => 'The Ship of Theseus',
                'artImg' => 'Img/Artwork/The Ship of Theseus.jpg',
                'category_id' => '2',
                'artStyle' => 'Abstract',
                'artPrice' => '700',
                'artDesc' => '(“The Ship of Theseus” – An acrylic painting on canvas about The Ship Of Theseus thought experiment in metaphysics from the ancient Greek era that raises the question of whether an object that has had all of its components replaced remains fundamentally the same object.)',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2020',
                'artWidth' => '195',
                'artHeight' => '120',
                'datetime' => '2022-04-14 09:50:10',
                'created_at' => '2022-04-14 09:50:10',
                'updated_at' => '2022-04-14 09:50:10',
            ],
            [
                'artID' => '8',
                'username' => 'minglee',
                'artistName' => 'Adam Ummar',
                'artName' => 'Bayangan Ahli Silap Nujum',
                'artImg' => 'Img/Artwork/Bayangan Ahli Silap Nujum.jpg',
                'category_id' => '2',
                'artStyle' => 'Abstract',
                'artPrice' => '850',
                'artDesc' => '(“Bayangan Ahli Silap Nujum” – A mixed media painting inspired by The Magician card in the Rider-Waite tarot card.)',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2020',
                'artWidth' => '195',
                'artHeight' => '120',
                'datetime' => '2022-01-03 18:34:20',
                'created_at' => '2022-01-03 18:34:20',
                'updated_at' => '2022-01-03 18:34:20',
            ],
            [
                'artID' => '9',
                'username' => 'minglee',
                'artistName' => 'Adam Ummar',
                'artName' => 'Bayangan Tiga Dewa',
                'artImg' => 'Img/Artwork/Bayangan Tiga Dewa.jpg',
                'category_id' => '2',
                'artStyle' => 'Abstract',
                'artPrice' => '850',
                'artDesc' => '(“Bayangan Tiga Dewa” – A mixed media painting that takes inspiration from Trimurti, the triadic deity of supreme divinity in Hinduism namely: Brahma, Vishnu & Shiva. The work explores humanity’s own capacity for creativity, preservation and destruction)',
                'artStatus' => 'SOLD',
                'artYear' => '2020',
                'artWidth' => '195',
                'artHeight' => '120',
                'datetime' => '2022-03-13 13:50:10',
                'created_at' => '2022-03-13 13:50:10',
                'updated_at' => '2022-03-13 13:50:10',
            ],
            [
                'artID' => '10',
                'username' => 'minglee',
                'artistName' => 'Craig Chadwick',
                'artName' => 'Hands on Move',
                'artImg' => 'Img/Artwork/Hands on Move.png',
                'category_id' => '3',
                'artStyle' => 'Modern Art',
                'artPrice' => '200',
                'artDesc' => '“Bro why my chair feels like hand one ah” – A piece that shows how we can have absolutely amazing and varying support systems that lift us up through everything and also I thought it would look cool.',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2020',
                'artWidth' => '195',
                'artHeight' => '120',
                'datetime' => '2022-06-09 13:34:55',
                'created_at' => '2022-06-09 13:34:55',
                'updated_at' => '2022-06-09 13:34:55',
            ],
            [
                'artID' => '11',
                'username' => 'minglee',
                'artistName' => 'Craig Chadwick',
                'artName' => 'Judgement',
                'artImg' => 'Img/Artwork/Judgement.png',
                'category_id' => '3',
                'artStyle' => 'Modern Art',
                'artPrice' => '175',
                'artDesc' => 'A piece about a woman that Creg had seen in his dream once and made him reflect on how we often go around presenting different faces to different people and forget that to every individual that knows us or has seen us, there is a different version of us that resides in their thoughts',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2020',
                'artWidth' => '195',
                'artHeight' => '120',
                'datetime' => '2022-01-11 23:50:10',
                'created_at' => '2022-01-11 23:50:10',
                'updated_at' => '2022-01-11 23:50:10',
            ],
            [
                'artID' => '12',
                'username' => 'minglee',
                'artistName' => 'Craig Chadwick',
                'artName' => 'Mirrored',
                'artImg' => 'Img/Artwork/Mirrored.png',
                'category_id' => '3',
                'artStyle' => 'Cosmic Art',
                'artPrice' => '18999',
                'artDesc' => 'A piece about Cregg ‘s previous self while moving on to become the person he is now.',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2020',
                'artWidth' => '195',
                'artHeight' => '120',
                'datetime' => '2022-04-04 01:23:31',
                'created_at' => '2022-04-04 01:23:31',
                'updated_at' => '2022-04-04 01:23:31',
            ],
            [
                'artID' => '13',
                'username' => 'minglee',
                'artistName' => 'Hasanah Bt Ahmad Surasa',
                'artName' => 'Pressure',
                'artImg' => 'Img/Artwork/Pressure.png',
                'category_id' => '1',
                'artStyle' => 'Cosmic Art',
                'artPrice' => '15200',
                'artDesc' => 'A basic comic panel that Hasanah had drawn.',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2019',
                'artWidth' => '160',
                'artHeight' => '95',
                'datetime' => '2022-06-18 10:50:18',
                'created_at' => '2022-06-18 10:50:18',
                'updated_at' => '2022-06-18 10:50:18',
            ],
            [
                'artID' => '14',
                'username' => 'minglee',
                'artistName' => 'Hasanah Bt Ahmad Surasa',
                'artName' => 'Witchcraft',
                'artImg' => 'Img/Artwork/Witchcraft.png',
                'category_id' => '1',
                'artStyle' => 'Cosmic Art',
                'artPrice' => '125',
                'artDesc' => 'Fan art for local girl band, Time Machine.',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2019',
                'artWidth' => '160',
                'artHeight' => '95',
                'datetime' => '2022-06-12 18:50:10',
                'created_at' => '2022-06-12 18:50:10',
                'updated_at' => '2022-06-12 18:50:10',
            ],
            [
                'artID' => '15',
                'username' => 'minglee',
                'artistName' => 'Hasanah Bt Ahmad Surasa',
                'artName' => 'Creeping',
                'artImg' => 'Img/Artwork/Creeping.png',
                'category_id' => '1',
                'artStyle' => 'Cosmic Art',
                'artPrice' => '300',
                'artDesc' => 'An artwork based on the song ‘She’s Creeping’ by Royal Blood.',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2019',
                'artWidth' => '160',
                'artHeight' => '95',
                'datetime' => '2022-03-23 18:50:18',
                'created_at' => '2022-03-23 18:50:18',
                'updated_at' => '2022-03-23 18:50:18',
            ],
            [
                'artID' => '16',
                'username' => 'minglee',
                'artistName' => 'Ilham',
                'artName' => 'Mary Has Some Bad News',
                'artImg' => 'Img/Artwork/Mary Has Some Bad News.png',
                'category_id' => '3',
                'artStyle' => 'Media Art',
                'artPrice' => '120',
                'artDesc' => '“Mary Has Some Bad News” – Inspired by Ilham’s favourite artist George Wylesol.',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '160',
                'artHeight' => '95',
                'datetime' => '2022-05-23 23:50:18',
                'created_at' => '2022-05-23 23:50:18',
                'updated_at' => '2022-05-23 23:50:18',
            ],
            [
                'artID' => '17',
                'username' => 'minglee',
                'artistName' => 'Ilham',
                'artName' => 'Intimacy',
                'artImg' => 'Img/Artwork/Intimacy.png',
                'category_id' => '4',
                'artStyle' => 'Media Art',
                'artPrice' => '150',
                'artDesc' => 'Intimacy',
                'artStatus' => 'SOLD',
                'artYear' => '2022',
                'artWidth' => '175',
                'artHeight' => '95',
                'datetime' => '2022-05-23 12:50:18',
                'created_at' => '2022-05-23 12:50:18',
                'updated_at' => '2022-05-23 12:50:18',
            ],
            [
                'artID' => '18',
                'username' => 'minglee',
                'artistName' => 'Ilham',
                'artName' => 'We Were Happy',
                'artImg' => 'Img/Artwork/We Were Happy.png',
                'category_id' => '3',
                'artStyle' => 'Media Art',
                'artPrice' => '100',
                'artDesc' => '“We Were Happy” Source: @unagilham on Instagram',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '175',
                'artHeight' => '95',
                'datetime' => '2022-11-29 10:53:18',
                'created_at' => '2022-11-29 10:53:18',
                'updated_at' => '2022-11-29 10:53:18',
            ],
            [
                'artID' => '19',
                'username' => 'minglee',
                'artistName' => 'Rizal Ariz',
                'artName' => 'Bloom your sadness away',
                'artImg' => 'Img/Artwork/Bloom your sadness away.png',
                'category_id' => '3',
                'artStyle' => 'Media Art',
                'artPrice' => '21000',
                'artDesc' => '“Bloom your sadness away” Source: @RizalAziz_ at Twitter',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '175',
                'artHeight' => '95',
                'datetime' => '2022-04-18 13:50:18',
                'created_at' => '2022-04-18 13:50:18',
                'updated_at' => '2022-04-18 13:50:18',
            ],
            [
                'artID' => '20',
                'username' => 'minglee',
                'artistName' => 'Rizal Ariz',
                'artName' => 'Glow and Grow',
                'artImg' => 'Img/Artwork/Glow and Grow.png',
                'category_id' => '3',
                'artStyle' => 'Media Art',
                'artPrice' => '7050',
                'artDesc' => '“Glow and Grow” Source: @RizalAziz_ at Twitter',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '175',
                'artHeight' => '95',
                'datetime' => '2022-06-18 10:50:18',
                'created_at' => '2022-06-18 10:50:18',
                'updated_at' => '2022-06-18 10:50:18',
            ],
            [
                'artID' => '21',
                'username' => 'minglee',
                'artistName' => 'Rizal Ariz',
                'artName' => 'Magi',
                'artImg' => 'Img/Artwork/Magi.png',
                'category_id' => '3',
                'artStyle' => 'Media Art',
                'artPrice' => '100',
                'artDesc' => '“Magi” Source: @RizalAziz_ at Twitter',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '175',
                'artHeight' => '95',
                'datetime' => '2022-04-18 10:50:18',
                'created_at' => '2022-04-18 10:50:18',
                'updated_at' => '2022-04-18 10:50:18',
            ],
            [
                'artID' => '22',
                'username' => 'minglee',
                'artistName' => 'Miriam Omar',
                'artName' => 'Secret Sungai',
                'artImg' => 'Img/Artwork/Secret Sungai.png',
                'category_id' => '2',
                'artStyle' => 'Nature',
                'artPrice' => '200',
                'artDesc' => '“Secret Sungai”',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '105',
                'artHeight' => '65',
                'datetime' => '2022-05-14 10:50:18',
                'created_at' => '2022-05-14 10:50:18',
                'updated_at' => '2022-05-14 10:50:18',
            ],
            [
                'artID' => '23',
                'username' => 'minglee',
                'artistName' => 'Miriam Omar',
                'artName' => 'Walk in the Meadow',
                'artImg' => 'Img/Artwork/Walk in the Meadow.png',
                'category_id' => '2',
                'artStyle' => 'Nature',
                'artPrice' => '9100',
                'artDesc' => '“Walk in the Meadow”',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '105',
                'artHeight' => '65',
                'datetime' => '2022-06-18 10:50:18',
                'created_at' => '2022-06-18 10:50:18',
                'updated_at' => '2022-06-18 10:50:18',
            ],
            [
                'artID' => '24',
                'username' => 'minglee',
                'artistName' => 'Miriam Omar',
                'artName' => 'Pintu Rahsia',
                'artImg' => 'Img/Artwork/Pintu Rahsia.png',
                'category_id' => '5',
                'artStyle' => 'Nature',
                'artPrice' => '20350',
                'artDesc' => '“Pintu Rahsia”',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '105',
                'artHeight' => '65',
                'datetime' => '2022-04-25 14:25:23',
                'created_at' => '2022-04-25 14:25:23',
                'updated_at' => '2022-04-25 14:25:23',
            ],
            [
                'artID' => '25',
                'username' => 'minglee',
                'artistName' => 'Pangrok Sulap',
                'artName' => 'Tetaplah Dengan Tradisi',
                'artImg' => 'Img/Artwork/Tetaplah Dengan Tradisi.png',
                'category_id' => '1',
                'artStyle' => 'Woodcut Printed',
                'artPrice' => '60',
                'artDesc' => '“Tetaplah Dengan Tradisi”',
                'artStatus' => 'SOLD',
                'artYear' => '2022',
                'artWidth' => '20',
                'artHeight' => '25',
                'datetime' => '2022-06-18 10:50:18',
                'created_at' => '2022-06-18 10:50:18',
                'updated_at' => '2022-06-18 10:50:18',
            ],
            [
                'artID' => '26',
                'username' => 'minglee',
                'artistName' => 'Pangrok Sulap',
                'artName' => 'Laut Adalah Kehidupan',
                'artImg' => 'Img/Artwork/Laut Adalah Kehidupan.png',
                'category_id' => '1',
                'artStyle' => 'Woodcut Printed',
                'artPrice' => '60',
                'artDesc' => '“Laut Adalah Kehidupan”',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '20',
                'artHeight' => '25',
                'datetime' => '2022-06-23 10:50:18',
                'created_at' => '2022-06-23 10:50:18',
                'updated_at' => '2022-06-23 10:50:18',
            ],
            [
                'artID' => '27',
                'username' => 'minglee',
                'artistName' => 'Pangrok Sulap',
                'artName' => 'Agama Tiada Bangsa',
                'artImg' => 'Img/Artwork/Agama Tiada Bangsa.png',
                'category_id' => '1',
                'artStyle' => 'Woodcut Printed',
                'artPrice' => '75',
                'artDesc' => '“Agama Tiada Bangsa”',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '20',
                'artHeight' => '25',
                'datetime' => '2022-09-19 10:50:18',
                'created_at' => '2022-09-19 10:50:18',
                'updated_at' => '2022-09-19 10:50:18',
            ],
            [
                'artID' => '28',
                'username' => 'minglee',
                'artistName' => 'Pangrok Sulap',
                'artName' => 'Di Belakang Orang Kampung',
                'artImg' => 'Img/Artwork/Di Belakang Orang Kampung.png',
                'category_id' => '1',
                'artStyle' => 'Woodcut Printed',
                'artPrice' => '75',
                'artDesc' => '“Di Belakang Orang Kampung”',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '20',
                'artHeight' => '25',
                'datetime' => '2022-11-30 10:50:51',
                'created_at' => '2022-11-30 10:50:51',
                'updated_at' => '2022-11-30 10:50:51',
            ],
            [
                'artID' => '29',
                'username' => 'minglee',
                'artistName' => 'Pangrok Sulap',
                'artName' => 'Raihkan Kepelbagaian',
                'artImg' => 'Img/Artwork/Raihkan Kepelbagaian.png',
                'category_id' => '1',
                'artStyle' => 'Woodcut Printed',
                'artPrice' => '75',
                'artDesc' => '“Raihkan Kepelbagaian”',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '20',
                'artHeight' => '25',
                'datetime' => '2022-10-01 18:23:18',
                'created_at' => '2022-10-01 18:23:18',
                'updated_at' => '2022-10-01 18:23:18',
            ],
            [
                'artID' => '30',
                'username' => 'minglee',
                'artistName' => 'Shan Shan Lim',
                'artName' => 'I Am Jungle',
                'artImg' => 'Img/Artwork/I Am Jungle.png',
                'category_id' => '5',
                'artStyle' => 'Nature',
                'artPrice' => '10550',
                'artDesc' => '“I Am Jungle”',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '95',
                'artHeight' => '50',
                'datetime' => '2022-09-02 03:50:34',
                'created_at' => '2022-09-02 03:50:34',
                'updated_at' => '2022-09-02 03:50:34',
            ],
            [
                'artID' => '31',
                'username' => 'minglee',
                'artistName' => 'Shan Shan Lim',
                'artName' => 'Subject Matter Art Kind Commission',
                'artImg' => 'Img/Artwork/Subject Matter Art Kind Commission.png',
                'category_id' => '2',
                'artStyle' => 'Geometric',
                'artPrice' => '25999',
                'artDesc' => '“Subject Matter Art Kind Commission”',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '50',
                'artHeight' => '75',
                'datetime' => '2022-05-12 10:50:44',
                'created_at' => '2022-05-12 10:50:44',
                'updated_at' => '2022-05-12 10:50:44',
            ],
            [
                'artID' => '32',
                'username' => 'minglee',
                'artistName' => 'Van Gogh',
                'artName' => 'Cafe Terrace at Night',
                'artImg' => 'Img/Artwork/Cafe Terrace At Night.jpg',
                'category_id' => '5',
                'artStyle' => 'Urban',
                'artPrice' => '40500',
                'artDesc' => '"I enormously enjoy painting on the spot at night. From Van Gogh"',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '150',
                'artHeight' => '100',
                'datetime' => '2022-12-03 19:19:12',
                'created_at' => '2022-12-03 19:19:12',
                'updated_at' => '2022-12-03 19:19:12',
            ],
            [
                'artID' => '33',
                'username' => 'minglee',
                'artistName' => 'Van Gogh',
                'artName' => 'The Bedroom',
                'artImg' => 'Img/Artwork/Bedroom.jpg',
                'category_id' => '7',
                'artStyle' => 'Urban',
                'artPrice' => '65000',
                'artDesc' => '"This is first of three paintings Van Gogh made of his bedroom in the Yellow House in Arles. It shows a modest bedroom, complete with single bed, bedside table, chair and mirror. The door to the left leads to the guest room where Gaugin stayed; the door to the right to the landing."',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '150',
                'artHeight' => '100',
                'datetime' => '2022-12-03 19:20:12',
                'created_at' => '2022-12-03 19:20:12',
                'updated_at' => '2022-12-03 19:20:12',
            ],
            [
                'artID' => '34',
                'username' => 'minglee',
                'artistName' => 'Van Gogh',
                'artName' => 'Starry Night over the Rhone',
                'artImg' => 'Img/Artwork/Starry Night over the Rhone.jpg',
                'category_id' => '2',
                'artStyle' => 'Urban',
                'artPrice' => '60500',
                'artDesc' => 'Starry Night is a bolder depiction of the night sky than van Gogh earlier (September 1888) work Starry Night over the Rhone.',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '150',
                'artHeight' => '100',
                'datetime' => '2022-12-03 19:21:12',
                'created_at' => '2022-12-03 19:21:12',
                'updated_at' => '2022-12-03 19:21:12',
            ],
            [
                'artID' => '35',
                'username' => 'minglee',
                'artistName' => 'Van Gogh',
                'artName' => 'Starry Night',
                'artImg' => 'Img/Artwork/Starry Night.jpg',
                'category_id' => '4',
                'artStyle' => 'Urban',
                'artPrice' => '90050',
                'artDesc' => '"At that time, Van Gogh was in the psychiatric hospital at Saint-Rémy. He enjoyed observing the night sky, writing “The sight of the stars always makes me dream” and he would have been able to see this view from the window of his room."',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '150',
                'artHeight' => '100',
                'datetime' => '2022-12-03 19:25:21',
                'created_at' => '2022-12-03 19:25:21',
                'updated_at' => '2022-12-03 19:25:21',
            ],
            [
                'artID' => '36',
                'username' => 'minglee',
                'artistName' => 'Van Gogh',
                'artName' => 'Irises (1889)',
                'artImg' => 'Img/Artwork/Irises.jpg',
                'category_id' => '6',
                'artStyle' => 'Urban',
                'artPrice' => '60000',
                'artDesc' => 'In total he painted five canvasses of sunflowers standing in vases between 1888 and 1889, using just three shades of yellow.',
                'artStatus' => 'SOLD',
                'artYear' => '2022',
                'artWidth' => '150',
                'artHeight' => '100',
                'datetime' => '2022-12-03 19:36:57',
                'created_at' => '2022-12-03 19:36:57',
                'updated_at' => '2022-12-03 19:36:57',
            ],
            [
                'artID' => '37',
                'username' => 'minglee',
                'artistName' => 'LEE LIK MING',
                'artName' => 'Lionel Messi',
                'artImg' => 'https://res.cloudinary.com/dyfzo7pcs/image/upload/v1670246548/t02nra67ughn7dib4yjy.png',
                'category_id' => '3',
                'artStyle' => 'Figurative',
                'artPrice' => '1999',
                'artDesc' => 'Lionel Messi - FIFA World Champion 2022',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '150',
                'artHeight' => '100',
                'datetime' => '2022-12-05 21:22:26',
                'created_at' => '2022-12-05 21:22:26',
                'updated_at' => '2022-12-05 21:22:26',
            ],
            [
                'artID' => '38',
                'username' => 'minglee',
                'artistName' => 'LEE LIK MING',
                'artName' => 'The Storm On The Sea Of Galilee',
                'artImg' => 'https://res.cloudinary.com/dyfzo7pcs/image/upload/v1670246625/j2anbuexacgyfqegwhgl.jpg',
                'category_id' => '3',
                'artStyle' => 'Abstract',
                'artPrice' => '1999',
                'artDesc' => 'The Storm On The Sea Of Galilee is one of Rembrandt’s most dynamic and dramatic works of art. The large-scale image has overwhelming effects that portray survival through a violent storm. The painting is popular for its incredible theme and the vivid brushstrokes that bring the canvas to life.',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '150',
                'artHeight' => '100',
                'datetime' => '2022-12-05 21:23:44',
                'created_at' => '2022-12-05 21:23:44',
                'updated_at' => '2022-12-05 21:23:44',
            ],
            [
                'artID' => '39',
                'username' => 'minglee',
                'artistName' => 'LEE LIK MING',
                'artName' => 'Paris Street In Rainy Weather',
                'artImg' => 'https://res.cloudinary.com/dyfzo7pcs/image/upload/v1670246577/gomqojko3s07ti1ww7q6.jpg',
                'category_id' => '3',
                'artStyle' => 'Nature',
                'artPrice' => '2999',
                'artDesc' => ' The life-like painting by French artist Gustave Caillebotte is considered one of his best works to date. It is a large oil-based painting that shows various individuals walking on a rainy day through the Place de Dublin and epitomized the modern paradigm. And even though this one is regarded as an Impressionist work of art, this masterpiece by Caillebotte is different for its apparent linearity and realism as compared to regular brush strokes.',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '150',
                'artHeight' => '100',
                'datetime' => '2022-12-05 21:22:56',
                'created_at' => '2022-12-05 21:22:56',
                'updated_at' => '2022-12-05 21:22:56',
            ],
            [
                'artID' => '40',
                'username' => 'minglee',
                'artistName' => 'LEE LIK MING',
                'artName' => 'Mexican Food',
                'artImg' => 'Img/Artwork/Mexican Food.png',
                'category_id' => '3',
                'artStyle' => 'Modern Art',
                'artPrice' => '500',
                'artDesc' => 'Let’s begin with Chiles En Nogada the most patriotic of Mexican meals made with the colors of the Mexican flag. Chiles En Nogada is made with green poblano chili peppers stuffed with a mixture of meats and spices known as picadillo.',
                'artStatus' => 'AVAILABLE',
                'artYear' => '2022',
                'artWidth' => '195',
                'artHeight' => '125',
                'datetime' => '2022-12-01 13:25:50',
                'created_at' => '2022-12-01 13:25:50',
                'updated_at' => '2022-12-01 13:25:50',
            ]

        ];
        Art::insert($data);
    }
}
